name: Build Docker Image

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-push-workflow:
    name: Build and Push Docker Image
    # TODO: uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    uses: ./.github/workflows/build-and-push-shared.yml
    with:
      image-name:  ls1intum/apollon_standalone
      docker-file: Dockerfile.redis
    secrets: inherit