name: Build and Deploy to Dev

on:
  pull_request:
    branches: [main]

jobs:
  build-dev-container:
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
  deploy-dev-container:
    needs: build-dev-container
    uses: ./.github/workflows/deploy-docker.yml
    secrets: inherit
    with:
      environment: Dev
      image-name: ls1intum/Apollon_standalone
      image-tag: "${{ needs.build-dev-container.outputs.image-tag }}"